version: '3'

services:
  db:
    container_name: introGraphQL_db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - $PWD/db:/data/db

  backend:
    container_name: introGraphQL_backend
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    command: npm run dev
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - db

  frontend:
    container_name: introGraphQL_frontend
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    command: npm run start
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
